'use client';

import { Note } from '@/lib/api';
import { Search, FileText, Clock } from 'lucide-react';
import { useState, useMemo } from 'react';

import { Loader2 } from 'lucide-react';

interface NotesGalleryProps {
    notes: Note[];
    isLoading?: boolean;
    onSelectNote: (note: Note) => void;
}

function formatTimeAgo(dateString: string): string {
    const date = new Date(dateString);
    const now = new Date();
    const seconds = Math.floor((now.getTime() - date.getTime()) / 1000);

    if (seconds < 60) return 'just now';
    if (seconds < 3600) return `${Math.floor(seconds / 60)}m ago`;
    if (seconds < 86400) return `${Math.floor(seconds / 3600)}h ago`;
    if (seconds < 604800) return `${Math.floor(seconds / 86400)}d ago`;
    return date.toLocaleDateString();
}

function getYouTubeThumb(videoId: string): string {
    return `https://img.youtube.com/vi/${videoId}/mqdefault.jpg`;
}

export function NotesGallery({ notes, isLoading, onSelectNote }: NotesGalleryProps) {
    const [search, setSearch] = useState('');

    const filteredNotes = useMemo(() => {
        if (!search.trim()) return notes;
        const query = search.toLowerCase();
        return notes.filter(
            (note) =>
                note.video_id.toLowerCase().includes(query) ||
                note.url.toLowerCase().includes(query) ||
                note.title?.toLowerCase().includes(query)
        );
    }, [notes, search]);

    // Loading state
    if (isLoading) {
        return (
            <div className="text-center py-12 text-muted-foreground">
                <Loader2 className="w-8 h-8 mx-auto mb-4 animate-spin text-primary" />
                <p>Loading notes...</p>
            </div>
        );
    }

    if (notes.length === 0) {
        return (
            <div className="text-center py-12 text-muted-foreground">
                <FileText className="w-12 h-12 mx-auto mb-4 opacity-50" />
                <p>No notes yet. Generate your first note above!</p>
            </div>
        );
    }

    return (
        <div className="space-y-4">
            <div className="flex items-center justify-between">
                <h2 className="text-xl font-semibold text-primary">All Notes(previously generated by others)</h2>
                <div className="relative">
                    <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground" />
                    <input
                        type="text"
                        placeholder="Search by video URL..."
                        value={search}
                        onChange={(e) => setSearch(e.target.value)}
                        className="pl-9 pr-4 py-2 text-sm rounded-lg border border-primary/20 bg-background focus:outline-none focus:ring-2 focus:ring-primary/30 w-64"
                    />
                </div>
            </div>

            <div className="grid gap-3">
                {filteredNotes.map((note) => (
                    <button
                        key={note.id}
                        onClick={() => onSelectNote(note)}
                        className="flex items-center gap-4 p-4 rounded-xl border border-primary/10 hover:border-primary/30 hover:bg-primary/5 transition-all text-left group"
                    >
                        {/* Thumbnail */}
                        <div className="w-24 h-16 rounded-lg overflow-hidden flex-shrink-0 bg-muted">
                            <img
                                src={getYouTubeThumb(note.video_id)}
                                alt={note.title || note.video_id}
                                className="w-full h-full object-cover"
                            />
                        </div>

                        {/* Info */}
                        <div className="flex-1 min-w-0">
                            <h3 className="font-medium text-foreground truncate group-hover:text-primary transition-colors">
                                {note.title || `Video ${note.video_id}`}
                            </h3>
                            <p className="text-sm text-muted-foreground truncate">
                                {note.url}
                            </p>
                        </div>

                        {/* Meta */}
                        <div className="flex-shrink-0 text-right">
                            {note.generation_cost !== undefined && note.generation_cost > 0 && (
                                <span className="text-xs px-2 py-1 rounded-lg border border-primary/20 text-primary font-medium">
                                    ${note.generation_cost.toFixed(4)}
                                </span>
                            )}
                            <div className="flex items-center gap-1 text-xs text-muted-foreground mt-1">
                                <Clock className="w-3 h-3" />
                                {formatTimeAgo(note.created_at)}
                            </div>
                        </div>
                    </button>
                ))}
            </div>

            {filteredNotes.length === 0 && search && (
                <div className="text-center py-8 text-muted-foreground">
                    No notes matching &quot;{search}&quot;
                </div>
            )}
        </div>
    );
}
