'use client';

import ReactMarkdown from 'react-markdown';
import { Prism as SyntaxHighlighter } from 'react-syntax-highlighter';
import { vscDarkPlus, oneLight } from 'react-syntax-highlighter/dist/esm/styles/prism';
import { Copy, Check, Download, FileText, FileCode, RefreshCw } from 'lucide-react';
import { useState, useRef } from 'react';
import { useReactToPrint } from 'react-to-print';

interface NoteViewerProps {
  content: string;
  onRegenerate?: () => void;
}

export function NoteViewer({ content, onRegenerate }: NoteViewerProps) {
  const contentRef = useRef<HTMLDivElement>(null);

  const handlePrint = useReactToPrint({
    contentRef: contentRef,
    documentTitle: "Technical Notes",
  });

  const handleDownloadMD = () => {
    const blob = new Blob([content], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'notes.md';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-4">
      <div className="flex justify-end gap-3 print:hidden">
        {onRegenerate && (
          <button
            onClick={onRegenerate}
            className="flex items-center gap-2 px-4 py-2 text-sm font-medium rounded-lg border border-primary/20 text-primary hover:bg-primary/5 transition-colors"
            title="Force regenerate notes from scratch"
          >
            <RefreshCw className="w-4 h-4" />
            Regenerate
          </button>
        )}
        <button
          onClick={() => handlePrint && handlePrint()}
          className="flex items-center gap-2 px-4 py-2 text-sm font-medium rounded-lg border border-primary/20 text-primary hover:bg-primary/5 transition-colors"
        >
          <FileText className="w-4 h-4" />
          Download PDF
        </button>
        <button
          onClick={handleDownloadMD}
          className="flex items-center gap-2 px-4 py-2 text-sm font-medium rounded-lg bg-primary text-primary-foreground hover:bg-primary/90 transition-colors shadow-sm"
        >
          <FileCode className="w-4 h-4" />
          Download MD
        </button>
      </div>

      <article 
        ref={contentRef}
        className="prose prose-stone dark:prose-invert max-w-none w-full bg-background p-8 md:p-12 rounded-xl shadow-sm border border-muted print:shadow-none print:border-none"
      >
        <div className="print:block hidden mb-8 text-center border-b pb-4">
            <h1 className="text-2xl font-bold">Technical Notes</h1>
            <p className="text-sm text-gray-500">Generated by YouTube Technical Note-Taker</p>
        </div>
        <ReactMarkdown
          components={{
            h1: ({node, ...props}) => <h1 className="text-3xl font-extrabold tracking-tight text-primary mb-6" {...props} />,
            h2: ({node, ...props}) => <h2 className="text-2xl font-bold border-b border-primary/20 pb-2 mt-8 mb-4" {...props} />,
            h3: ({node, ...props}) => <h3 className="text-xl font-semibold text-primary/90 mt-6 mb-3" {...props} />,
            a: ({node, ...props}) => <a className="text-primary hover:text-primary/80 no-underline border-b border-primary/30 hover:border-primary transition-colors" {...props} />,
            code({ node, inline, className, children, ...props }: any) {
              const match = /language-(\w+)/.exec(className || '');
              const codeString = String(children).replace(/\n$/, '');
              
              if (!inline && match) {
                return (
                  <div className="relative group rounded-lg overflow-hidden my-6 shadow-md border border-muted-foreground/20 print:border-gray-300">
                    <div className="absolute right-2 top-2 z-10 opacity-0 group-hover:opacity-100 transition-opacity print:hidden">
                      <CopyButton code={codeString} />
                    </div>
                    <SyntaxHighlighter
                      {...props}
                      style={vscDarkPlus}
                      language={match[1]}
                      PreTag="div"
                      customStyle={{ margin: 0, padding: '1.5rem', borderRadius: '0', fontSize: '0.9em' }}
                    >
                      {codeString}
                    </SyntaxHighlighter>
                  </div>
                );
              }
              return (
                <code {...props} className="bg-muted px-1.5 py-0.5 rounded text-sm font-mono text-primary font-medium">
                  {children}
                </code>
              );
            },
          }}
        >
          {content}
        </ReactMarkdown>
      </article>
    </div>
  );
}

function CopyButton({ code }: { code: string }) {
  const [copied, setCopied] = useState(false);

  const handleCopy = () => {
    navigator.clipboard.writeText(code);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <button
      onClick={handleCopy}
      className="p-1.5 rounded-md bg-stone-800/80 hover:bg-stone-700/80 text-stone-200 transition-colors backdrop-blur-sm"
      title="Copy code"
    >
      {copied ? <Check className="w-4 h-4 text-green-400" /> : <Copy className="w-4 h-4" />}
    </button>
  );
}
